
server:
  port: 8081
pubsub:
  projectId: my-demo-project-341408
  topicId: demo_topic
  subscriberId: demo_topic-sub

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 515057049362-bbi4tg6kpgp4s9vpkpm1b1o5q2mdbhtd.apps.googleusercontent.com
#            clientSecret: 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

#          accessTokenUri: https://www.googleapis.com/oauth2/v3/token
#          userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#          tokenName: oauth_token
#          authenticationScheme: query
#          clientAuthenticationScheme: form
#          scope: email

#  resource:
#    userInfoUri: https://www.googleapis.com/userinfo/v2/me
#    preferTokenInfo: false